language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer update --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/behat/behat/bin/behat

after_script:
  - vendor/bin/coveralls